// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/victor-nach/postr-backend/internal/services/usersservice (interfaces: usersRepo)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_repo.go -package=mocks github.com/victor-nach/postr-backend/internal/services/usersservice usersRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/victor-nach/postr-backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
	isgomock struct{}
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockusersRepo) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockusersRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockusersRepo)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockusersRepo) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockusersRepoMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockusersRepo)(nil).Create), ctx, user)
}

// Get mocks base method.
func (m *MockusersRepo) Get(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockusersRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockusersRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockusersRepo) List(ctx context.Context, pageNumber, pageSize int) (domain.PaginatedUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pageNumber, pageSize)
	ret0, _ := ret[0].(domain.PaginatedUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockusersRepoMockRecorder) List(ctx, pageNumber, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockusersRepo)(nil).List), ctx, pageNumber, pageSize)
}

// Validate mocks base method.
func (m *MockusersRepo) Validate(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockusersRepoMockRecorder) Validate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockusersRepo)(nil).Validate), ctx, userID)
}
